export const Types = {
    SHOW_SIGN_IN_WINDOW: 'SHOW_SIGN_IN_WINDOW',
    HIDE_SIGN_IN_WINDOW: 'HIDE_SIGN_IN_WINDOW',
    SHOW_SIGN_UP_WINDOW: 'SHOW_SIGN_UP_WINDOW',
    HIDE_SIGN_UP_WINDOW: 'HIDE_SIGN_UP_WINDOW',
    SHOW_CREATE_CHANNEL_WINDOW: 'SHOW_CREATE_CHANNEL_WINDOW',
    HIDE_CREATE_CHANNEL_WINDOW: 'HIDE_CREATE_CHANNEL_WINDOW',
    SHOW_MESSENGER: 'SHOW_MESSENGER',
    HIDE_MESSENGER: 'HIDE_MESSENGER',
    SET_CHANNELS: 'SET_CHANNELS',
    SET_TOKEN: 'SET_TOKEN',
    SELECT_CURRENT_CHANNEL: 'SELECT_CURRENT_CHANNEL'
}
