
export const Types = {
    SHOW_SIGN_IN_WINDOW: 'SHOW_SIGN_IN_WINDOW',
    HIDE_SIGN_IN_WINDOW: 'HIDE_SIGN_IN_WINDOW',

    SHOW_SIGN_UP_WINDOW: 'SHOW_SIGN_UP_WINDOW',
    HIDE_SIGN_UP_WINDOW: 'HIDE_SIGN_UP_WINDOW',

    SHOW_CREATE_CHANNEL_WINDOW: 'SHOW_CREATE_CHANNEL_WINDOW',
    HIDE_CREATE_CHANNEL_WINDOW: 'HIDE_CREATE_CHANNEL_WINDOW',

    SHOW_MESSENGER: 'SHOW_MESSENGER',
    HIDE_MESSENGER: 'HIDE_MESSENGER',

    SHOW_BG_LAYER: 'SHOW_BG_LAYER',
    HIDE_BG_LAYER: 'HIDE_BG_LAYER',

    SHOW_SEARCH_CHANNEL_WINDOW: 'SHOW_SEARCH_CHANNEL_WINDOW',
    HIDE_SEARCH_CHANNEL_WINDOW: 'HIDE_SEARCH_CHANNEL_WINDOW',

    SET_CHANNELS: 'SET_CHANNELS',
    SET_TOKEN: 'SET_TOKEN',
    SELECT_CURRENT_CHANNEL: 'SELECT_CURRENT_CHANNEL',
    HIDE_SPLASH_SCREEN: 'HIDE_SPLASH_SCREEN',
    LOG_OUT: 'LOG_OUT',
    SET_ALL_CHANNELS: 'SET_ALL_CHANNELS',
    FIND_CHANNEL: 'FIND_CHANNEL',
    NEW_MESSAGE: 'NEW_MESSAGE',
    SET_MESSAGES: 'SET_MESSAGES',
    SET_ID: 'SET_ID',
}
